### ISSUE TITLE
我的Java版本是18，为啥它检测不到。

### ISSUE THREAD

**Issue by luoyuankong** [Xwdit/RainyBot-Core#46]
请问一下，这个是什么问题。截图如下：
![Snipaste_2023-01-15_19-18-48](https://user-images.githubusercontent.com/93425616/212537632-b01eed8e-ea6c-4796-836b-e4513a7a511a.png)

**Comment by Xwdit** [comment]
java1.8不是java18，您可以在这里下载需要的java版本：https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe
